spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest

logging:
  level:
    com.javatechie.saga: INFO
    org.springframework.kafka: INFO

server:
  port: 8082
